-- ========================================================
-- NAWI VERIFY — DEMO SEED DATA (OPTIONAL)
-- ========================================================
-- Note: Replace User UUIDs with actual auth.users IDs after signing up in Supabase!

-- Seed sample instruments
INSERT INTO public.instruments (
  id,
  instrument_code,
  manufacturer,
  model,
  serial_number,
  instrument_type,
  accuracy_class,
  max_capacity,
  max_unit,
  min_capacity,
  min_unit,
  scale_interval_d,
  scale_interval_d_unit,
  verification_interval_e,
  verification_interval_e_unit,
  verification_intervals_n,
  digital_indication,
  zero_setting_type,
  tare_device_available,
  tare_type,
  maximum_tare_effect,
  maximum_tare_unit,
  load_receptor_type,
  number_of_supports,
  status
) VALUES
(
  'a1b2c3d4-e5f6-7890-1234-56789abcdef0',
  'INS-2026-001',
  'Mettler Toledo Metrology Ltd.',
  'PrecisionPro XP-600',
  'XP600-2026-8841',
  'Electronic Weighing Scale',
  'Class II',
  600,
  'g',
  5,
  'g',
  0.1,
  'g',
  0.1,
  'g',
  6000,
  true,
  'SEMI_AUTOMATIC',
  true,
  'SUBTRACTIVE',
  600,
  'g',
  'PLATFORM',
  4,
  'Compliant'
),
(
  'b2c3d4e5-f6a7-8901-2345-6789abcdef01',
  'INS-2026-002',
  'A&D Weighing Systems Ltd.',
  'HeavyLoad VX-3000',
  'VX3000-9921',
  'Platform Scale',
  'Class III',
  30,
  'kg',
  0.1,
  'kg',
  5,
  'g',
  5,
  'g',
  6000,
  true,
  'SEMI_AUTOMATIC',
  true,
  'SUBTRACTIVE',
  10,
  'kg',
  'PLATFORM',
  4,
  'Compliant'
),
(
  'c3d4e5f6-a7b8-9012-3456-789abcdef012',
  'INS-2026-006',
  'MetriScale Instruments Corp.',
  'DirectWeigh NT-15 (No Tare)',
  'NT15-2026-9021',
  'Bench Scale',
  'Class III',
  15,
  'kg',
  0.05,
  'kg',
  2,
  'g',
  2,
  'g',
  7500,
  true,
  'SEMI_AUTOMATIC',
  false,
  'NONE',
  0,
  'kg',
  'PLATFORM',
  4,
  'Under Evaluation'
)
ON CONFLICT (instrument_code) DO NOTHING;
